Adds outline and selective bloom
react-spring/react-postprocessing pull request #24
Opened 2020-08-08 19:27 UTC by gsimone

2020-08-08 20:59 UTC, stephencorwin commented on src/effects/Outline.tsx
> +    () =>{
It looks like maybe prettier failed on commit here. I'll submit a PR shortly to convert to a more similar setup to the v5 branch in r3f

2020-08-31 20:26 UTC, talentlessguy requested changes
Pls remove `?` from partial cuz it already makes all properties optional

2020-08-31 20:26 UTC, talentlessguy commented on src/effects/ColorAverage.tsx
> +  blendFunction?: BlendFunction
`Partial` type already makes properties optional. No need for `?` :D

ts doc: https://www.typescriptlang.org/docs/handbook/utility-types.html#partialtype

2020-08-31 20:26 UTC, talentlessguy commented on src/effects/Outline.tsx
> +    selectionLayer?: number
same here, `Partial<T>` u don't have to put `?`

2020-08-31 20:26 UTC, talentlessguy commented on src/effects/SelectiveBloom.tsx
> +  }>
....and same for here....

2020-08-31 20:29 UTC, talentlessguy commented
I will add the example to the PR, to see it works as it should :D

2020-09-01 15:40 UTC, CharlieHess commented
I synced this branch with `yarn add https://github.com/react-spring/react-postprocessing.git/#adds-select-effects` to test the outline effect and found selection not updating on mouse over. My legacy effects chain from three/examples works with the same code so something might be wrong here.

2020-09-07 00:01 UTC, stephencorwin approved these changes

2020-09-07 07:45 UTC, merged